### PR TITLE
Update to noddity-retrieval 1.5

### PR DESCRIPTION
**Pull request by ArtskydJ**

### CODE REVIEW

**Comment by ArtskydJ** [comment]
```bash
$ npm test
> noddity-butler@2.1.1 test /home/travis/build/TehShrike/noddity-butler
> tape ./test/*.js
TAP version 13
# no server running
# getting all posts with a server error
ok 1 error getting all posts
# getting most recent posts with a server error
ok 2 error getting most recent posts
# getting local posts with a server error
ok 3 error getting local posts
# No file with that name
ok 4 error looking up doesNotExist.lol
# Bad index
/home/travis/build/TehShrike/noddity-butler/lib/post_manager.js:40
		var fns = arrayOfFileNames.map(function(filename) {
		                           ^
TypeError: undefined is not a function
    at getPosts (/home/travis/build/TehShrike/noddity-butler/lib/post_manager.js:40:30)
    at /home/travis/build/TehShrike/noddity-butler/lib/index_manager.js:54:5
    at /home/travis/build/TehShrike/noddity-butler/node_modules/levelup-cache/index.js:87:5
    at /home/travis/build/TehShrike/noddity-butler/node_modules/levelup-cache/index.js:101:47
    at /home/travis/build/TehShrike/noddity-butler/node_modules/subleveldown/node_modules/levelup/lib/levelup.js:230:7
    at Immediate._onImmediate (/home/travis/build/TehShrike/noddity-butler/node_modules/level-mem/node_modules/memdown/memdown.js:125:5)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```
Was `noddity-retrieval@1.5` a breaking change?

**Comment by ArtskydJ** [comment]
I think the issue is a difference between noddity-retrieval@1.3 and noddity-retrieval@1.5.

If 1.3 comes across invalid json, it will do `cb(new Error('err'))`
If 1.5 comes across invalid json, it will do `cb(null, undefined)`

@TehShrike what should we do to resolve this?

**Comment by ArtskydJ** [comment]
Actually I was wrong, both call back with an error.

**Comment by ArtskydJ** [comment]
Ok, the issue (I think) is that it is not using the latest changes in noddity-retrieval

**Comment by TehShrike** [comment]
Yup, looks like that fixed it.

**Comment by TehShrike** [comment]
If I deploy this as a new feature version, are you down to do a quick integration test by running the noddity-installer?

**Comment by ArtskydJ** [comment]
> ... are you down to do a quick integration test ... ?

I'd be able to do that sometime tonight.

---

> ... new feature version

Are you saying that this would be a minor bump?

**Comment by TehShrike** [comment]
Yeah, I'd lean towards a minor bump because even though it should be a backwards-compatible change, switching the XHR library is a big enough change I don't want to release it as a patch release.

**Comment by TehShrike** [comment]
Published as 2.2.0

**Comment by ArtskydJ** [comment]
I ran `noddity-installer` and played around with it for a bit; seems to work fine.

**Comment by TehShrike** [comment]
w00t!

**Pull request merged**
